version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/bookstore
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=c0o3xue87!q1@el1+#j@96!9uj3me%2ba-mqv1rqae!^6++*$$3"
      - "DJANGO_DEBUG=True"
      - "DJANGO_DB_PASS=postgres"
      - "DJANGO_TIMEZONE=Africa/Nairobi"

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: